### ISSUE TITLE
systemd and cluster join

### ISSUE THREAD

**Issue by jeromew** [oravirt/ansible-cockroachdb#1]
Hello,
Thanks for your work on these scripts. It helps me understand how to setup a cockroach cluster with ansible.

Currently, the systemd service script does not use "join". I don't understand how the nodes are supposed to know which cluster they should join upon a server restart for example ? Does a node remember where the cluster can be joined ?

**Comment by oravirt** [comment]
Hi, 
Thank you!

Yes the information about the other nodes are stored on disk in the --store directory, and that is why it is ok to omit the --join flag on a restart after a node is part of  a cluster.

**Comment by jeromew** [comment]
ok I understand. Thanks. 
for info it seems that cockroachdb 1.1.0 changed the init phase - cf https://www.cockroachlabs.com/docs/stable/manual-deployment.html#step-3-initialize-the-cluster
